export const REQUEST_CARRIERS = 'REQUEST_CARRIERS';
export const SUCCESS_CARRIERS = 'SUCCESS_CARRIERS';
export const FAILURE_CARRIERS = 'FAILURE_CARRIERS';

export const REQUEST_PLACES = 'REQUEST_PLACES';
export const SUCCESS_PLACES = 'SUCCESS_PLACES';
export const FAILURE_PLACES = 'FAILURE_PLACES';

export const REQUEST_MARKERS = 'REQUEST_MARKERS';
export const SUCCESS_MARKERS = 'SUCCESS_MARKERS';
export const FAILURE_MARKERS = 'FAILURE_MARKERS';

export const DELETE_CARRIERS = 'DELETE_CARRIERS';
export const DELETE_PLACES = 'DELETE_PLACES';
export const DELETE_MARKERS = 'DELETE_MARKERS';

export const ADD_PLACE = 'ADD_PLACE';
export const ADD_CARRIER = 'ADD_CARRIER';

export const CHANGE_TAB = 'CHANGE_TAB';